title = "Nebulight"  # From Git
gitRepoUrl = "https://github.com/re-sync-dev/Nebulight" # From Git

gitSourceBranch = "main"
changelog = false
classOrder = []

[docusaurus]
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "re-sync-dev"
projectName = "Nebulight"
url = "https://re-sync-dev.github.io"
baseUrl = "/Nebulight"
tagline = "An open source lighting preset creation and application library for Roblox."

[footer]
style = "dark"
copyright = "Copyright © 2025 Re-Sync. Built with Moonwave and Docusaurus"
