[package]
name = "vyon/nebulight"
description = "Nebulight is an open source lighting preset creation and application library for Roblox"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Vyon (https://github.com/Vyon)"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]